spring.application.name=CampusBotApplication
server.port=8080
ai.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent
ai.api.key=AIzaSyDD7ZaxESxZ21bTre9HGtSYptByPTKUwnY